FUNCTION zmm_jb_bloq_prov.
*"----------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     REFERENCE(P_FECHA) TYPE  DATUM
*"----------------------------------------------------------------------

*------------------------------------------------*
*------------------------------------------------*
*...
*------------------------------------------------*
* Generated by JHERNANDEV 17.04.2026, 11:23:02
*------------------------------------------------*


  DATA it_ekpo TYPE SORTED TABLE OF st_ekpo WITH UNIQUE KEY ebeln ebelp bewtp budat cputm buzei.
  DATA it_historial TYPE SORTED TABLE OF st_ekpo WITH UNIQUE KEY ebeln ebelp bewtp budat cputm buzei.

  DATA: vl_fecha      TYPE datum, vl_posiciones TYPE i.
  DATA: vl_ebelp  TYPE ebelp, c_bloqueo.

  DATA: lo_vendor TYPE REF TO zcl_des_bloqueo_proveedor,
        ls_status TYPE zcl_des_bloqueo_proveedor=>ty_status,
        vl_log    TYPE  zcl_des_bloqueo_proveedor=>tt_log.

  CREATE OBJECT lo_vendor.


  IF  p_fecha IS INITIAL.
    vl_fecha = sy-datum.
  ELSE.
    vl_fecha = p_fecha.
  ENDIF.


*.Adopt this select statement to your needs
  SELECT DISTINCT
    b~aedat,
    c~ebeln,
    c~ebelp,
    c~vgabe,
    c~bewtp,
    c~belnr,
    c~budat,
    c~cputm,
    c~buzei,
    b~lifnr,
    b~bukrs,
    b~ekorg
    FROM ekpo AS a
     LEFT OUTER JOIN ekko AS b
      ON b~ebeln EQ a~ebeln
     LEFT OUTER JOIN ekbe AS c
      ON c~ebeln EQ a~ebeln
      AND c~ebelp EQ a~ebelp
     LEFT OUTER JOIN ml_esll AS d
      ON d~packno EQ c~packno
    WHERE b~aedat EQ @vl_fecha AND
        ( a~ebeln EQ b~ebeln )
    AND ( a~pstyp EQ '9' )
    AND d~del NE 'X'
   INTO TABLE @it_ekpo
    .

  IF it_ekpo IS NOT INITIAL.
    DATA(it_ekko) = it_ekpo[].

    DELETE ADJACENT DUPLICATES FROM it_ekko COMPARING ebeln.

    LOOP AT it_ekko INTO DATA(wa_ekko).

      it_historial = FILTER #( it_ekpo WHERE ebeln = wa_ekko-ebeln ).
      DESCRIBE TABLE it_historial LINES vl_posiciones.
      vl_ebelp = '00010'.
      DO vl_posiciones TIMES.
        READ TABLE it_historial INTO DATA(wa_entrada) WITH KEY ebeln = wa_ekko-ebeln ebelp = vl_ebelp bewtp = 'E'.
        IF sy-subrc EQ 0. "si tiene entrada de servicio se valida el tiempo que se tiene para subir al menos la fact pre
          "Calcular fecha/horas
          READ TABLE it_historial WITH KEY ebeln = wa_ekko-ebeln ebelp = vl_ebelp bewtp = 'T' TRANSPORTING NO FIELDS.
          IF sy-subrc NE 0. "si no ya tiene una factura preeliminar

            PERFORM calc_tiempo USING wa_entrada "48 hrs.
                                  CHANGING c_bloqueo.

            IF c_bloqueo EQ 'X'.
              "Validamos si ya esta bloqueado el proveedor para evitar la rutina innecesaria
              TRY.
                  lo_vendor->get_block_status(
                    EXPORTING
                      iv_lifnr  = wa_entrada-lifnr
                    IMPORTING
                      es_status = ls_status
                  ).

                  IF ls_status-central_fi = abap_true
                       AND ls_status-all_bukrs_block = abap_true
                       AND ls_status-all_ekorg_block = abap_true.

                    " Ya está completamente bloqueado → no hacer nada

                  ELSE.
                    TRY.
                        lo_vendor->block_vendor(
                          EXPORTING
                            iv_lifnr     = wa_entrada-lifnr
                            iv_do_commit = abap_true
                          IMPORTING
                            et_log       = vl_log
                        ).
                      CATCH zcx_des_bloqueo_proveedor INTO DATA(lx). " Excepción Bloqueo Proveedor
                        WRITE lx->mv_text .
                    ENDTRY.
                  ENDIF.


                CATCH zcx_des_bloqueo_proveedor INTO lx.
                  WRITE lx->mv_text .
              ENDTRY.
              """"""""""""""""""""""""""""""""""""""""""""""""""""""""222
            ENDIF.
          ENDIF.
        ENDIF.
        vl_ebelp = vl_ebelp + 10.
      ENDDO.

    ENDLOOP.


  ENDIF.
ENDFUNCTION.

FORM calc_tiempo USING p_wa TYPE st_ekpo
                 CHANGING p_bloqueo.


  DATA: lv_date       TYPE datum,
        lv_time       TYPE uzeit,
        lv_timestamp  TYPE timestampl,
        lv_budatetime TYPE timestampl.


*  SORT us_tabla BY budat cputm DESCENDING.
*  READ TABLE us_tabla INTO DATA(wa_q) INDEX 1.

  " Convertir a timestamp "tiempo de consulta
  CONVERT DATE sy-datum TIME sy-uzeit
          INTO TIME STAMP lv_timestamp
          TIME ZONE sy-zonlo.


  CONVERT DATE p_wa-budat TIME p_wa-cputm
          INTO TIME STAMP lv_budatetime
          TIME ZONE sy-zonlo.

  cl_abap_tstmp=>subtract(
    EXPORTING
      tstmp1 = lv_timestamp
      tstmp2 = lv_budatetime
    RECEIVING
      r_secs = DATA(lv_secs)
  ).

  DATA(lv_hours) = lv_secs / 3600.

  IF lv_hours GT 48.
    "bloquear proveedor
    p_bloqueo = 'X'.
  ENDIF.

ENDFORM.

FORM bloque_proveedor USING iv_lifnr TYPE lifnr
                            iv_block TYPE abap_bool.

  DATA: lv_flag TYPE c LENGTH 1.

  DATA: ls_lfa1_old TYPE lfa1,
        ls_lfa1_new TYPE lfa1.

  DATA: lt_lfb1_old TYPE STANDARD TABLE OF lfb1,
        ls_lfb1_old TYPE lfb1,
        ls_lfb1_new TYPE lfb1.

  DATA: lt_lfm1_old TYPE STANDARD TABLE OF lfm1,
        ls_lfm1_old TYPE lfm1,
        ls_lfm1_new TYPE lfm1.

  DATA: ls_dummy_lfb1_old TYPE lfb1,
        ls_dummy_lfb1_new TYPE lfb1,
        ls_dummy_lfm1_old TYPE lfm1,
        ls_dummy_lfm1_new TYPE lfm1.

  DATA: lt_xlfas TYPE STANDARD TABLE OF flfas,
        lt_ylfas TYPE STANDARD TABLE OF flfas,
        lt_xlfb5 TYPE STANDARD TABLE OF flfb5,
        lt_ylfb5 TYPE STANDARD TABLE OF flfb5,
        lt_xlfbk TYPE STANDARD TABLE OF flfbk,
        lt_ylfbk TYPE STANDARD TABLE OF flfbk,
        lt_xlfza TYPE STANDARD TABLE OF flfza,
        lt_ylfza TYPE STANDARD TABLE OF flfza.

  "---------------------------------------------
  " X = bloquear / SPACE = desbloquear
  "---------------------------------------------
  IF iv_block = abap_true.
    lv_flag = 'X'.
  ELSE.
    CLEAR lv_flag.
  ENDIF.

  "---------------------------------------------
  " 1) Leer datos generales del proveedor
  "---------------------------------------------
  SELECT SINGLE *
    INTO ls_lfa1_old
    FROM lfa1
   WHERE lifnr = iv_lifnr.

  IF sy-subrc <> 0.
    MESSAGE e398(00) WITH 'Proveedor inexistente en LFA1'.
  ENDIF.

  ls_lfa1_new = ls_lfa1_old.

  " Bloqueo/desbloqueo central contable
  ls_lfa1_new-sperr = lv_flag.

  " Bloqueo/desbloqueo central de compras
  ls_lfa1_new-sperm = lv_flag.

  "---------------------------------------------
  " 2) Procesar todas las sociedades (LFB1)
  "---------------------------------------------
  SELECT *
    INTO TABLE lt_lfb1_old
    FROM lfb1
   WHERE lifnr = iv_lifnr.

  LOOP AT lt_lfb1_old INTO ls_lfb1_old.

    ls_lfb1_new = ls_lfb1_old.

    " Bloqueo/desbloqueo por sociedad
    ls_lfb1_new-sperr = lv_flag.

    CALL FUNCTION 'VENDOR_UPDATE' IN UPDATE TASK
      EXPORTING
        i_lfa1  = ls_lfa1_new
        i_lfb1  = ls_lfb1_new
        i_lfm1  = ls_dummy_lfm1_new
        i_ylfa1 = ls_lfa1_old
        i_ylfb1 = ls_lfb1_old
        i_ylfm1 = ls_dummy_lfm1_old
      TABLES
        t_xlfas = lt_xlfas
        t_xlfb5 = lt_xlfb5
        t_xlfbk = lt_xlfbk
        t_xlfza = lt_xlfza
        t_ylfas = lt_ylfas
        t_ylfb5 = lt_ylfb5
        t_ylfbk = lt_ylfbk
        t_ylfza = lt_ylfza.

  ENDLOOP.

  "---------------------------------------------
  " 3) Procesar todas las orgs. de compras (LFM1)
  "---------------------------------------------
  SELECT *
    INTO TABLE lt_lfm1_old
    FROM lfm1
   WHERE lifnr = iv_lifnr.

  LOOP AT lt_lfm1_old INTO ls_lfm1_old.

    ls_lfm1_new = ls_lfm1_old.

    " Bloqueo/desbloqueo por organización de compras
    ls_lfm1_new-sperm = lv_flag.

    CALL FUNCTION 'VENDOR_UPDATE' IN UPDATE TASK
      EXPORTING
        i_lfa1  = ls_lfa1_new
        i_lfb1  = ls_dummy_lfb1_new
        i_lfm1  = ls_lfm1_new
        i_ylfa1 = ls_lfa1_old
        i_ylfb1 = ls_dummy_lfb1_old
        i_ylfm1 = ls_lfm1_old
      TABLES
        t_xlfas = lt_xlfas
        t_xlfb5 = lt_xlfb5
        t_xlfbk = lt_xlfbk
        t_xlfza = lt_xlfza
        t_ylfas = lt_ylfas
        t_ylfb5 = lt_ylfb5
        t_ylfbk = lt_ylfbk
        t_ylfza = lt_ylfza.

  ENDLOOP.

  "---------------------------------------------
  " 4) Ejecutar update task
  "---------------------------------------------
  COMMIT WORK AND WAIT.
ENDFORM.
*FORM valida_bloqueo USING p_lifnr TYPE lifnr.
*
*
*
*
*  DATA: ls_lfa1 TYPE lfa1,
*        lt_lfb1 TYPE STANDARD TABLE OF lfb1,
*        lt_lfm1 TYPE STANDARD TABLE OF lfm1,
*        ls_lfb1 TYPE lfb1,
*        ls_lfm1 TYPE lfm1.
*
*  CLEAR es_status.
*  es_status-lifnr = p_lifnr.
*
*  "-----------------------------------
*  " LFA1 (bloqueos centrales)
*  "-----------------------------------
*  SELECT SINGLE *
*    INTO ls_lfa1
*    FROM lfa1
*   WHERE lifnr = p_lifnr.
*
*  es_status-central_fi = xsdbool( ls_lfa1-sperr = 'X' ).
*  es_status-central_mm = xsdbool( ls_lfa1-sperm = 'X' ).
*
*  "-----------------------------------
*  " LFB1 (sociedades)
*  "-----------------------------------
*  SELECT *
*    INTO TABLE lt_lfb1
*    FROM lfb1
*   WHERE lifnr = p_lifnr.
*
*  IF lt_lfb1 IS NOT INITIAL.
*
*    DATA(lv_total_bukrs) = lines( lt_lfb1 ).
*    DATA(lv_block_bukrs) = 0.
*
*    LOOP AT lt_lfb1 INTO ls_lfb1.
*      IF ls_lfb1-sperr = 'X'.
*        lv_block_bukrs = lv_block_bukrs + 1.
*      ENDIF.
*    ENDLOOP.
*
*    es_status-any_bukrs_block = xsdbool( lv_block_bukrs > 0 ).
*    es_status-all_bukrs_block = xsdbool( lv_block_bukrs = lv_total_bukrs ).
*
*  ENDIF.
*
*  "-----------------------------------
*  " LFM1 (org. compras)
*  "-----------------------------------
*  SELECT *
*    INTO TABLE lt_lfm1
*    FROM lfm1
*   WHERE lifnr = p_lifnr.
*
*  IF lt_lfm1 IS NOT INITIAL.
*
*    DATA(lv_total_ekorg) = lines( lt_lfm1 ).
*    DATA(lv_block_ekorg) = 0.
*
*    LOOP AT lt_lfm1 INTO ls_lfm1.
*      IF ls_lfm1-sperm = 'X'.
*        lv_block_ekorg = lv_block_ekorg + 1.
*      ENDIF.
*    ENDLOOP.
*
*    es_status-any_ekorg_block = xsdbool( lv_block_ekorg > 0 ).
*    es_status-all_ekorg_block = xsdbool( lv_block_ekorg = lv_total_ekorg ).
*
*  ENDIF.
*
*
*ENDFORM.
