PROCESS BEFORE OUTPUT.
MODULE STATUS_1002.
CALL SUBSCREEN SUBSCREEN_02 INCLUDING sy-repid gv_numsubscr.
MODULE PBO_1002.
*
PROCESS AFTER INPUT.
CALL SUBSCREEN SUBSCREEN_02.
MODULE USER_COMMAND_1002.
MODULE PAI_1002.
