PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCO_TT_CECOAUT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCO_TT_CECOAUT-KOKRS .
    FIELD ZCO_TT_CECOAUT-BNAME .
    FIELD ZCO_TT_CECOAUT-KOSTL .
    FIELD ZCO_TT_CECOAUT-AFNAM .
    FIELD ZCO_TT_CECOAUT-WERKS .
    FIELD ZCO_TT_CECOAUT-COMODIN .
    FIELD ZCO_TT_CECOAUT-EMAIL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCO_TT_CECOAUT-KOKRS .
    FIELD ZCO_TT_CECOAUT-BNAME .
    FIELD ZCO_TT_CECOAUT-KOSTL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
