PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCO_TT_AUTPRES CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCO_TT_AUTPRES-CODLIB .
    FIELD ZCO_TT_AUTPRES-BUKRS .
    FIELD ZCO_TT_AUTPRES-KOSTL .
    FIELD ZCO_TT_AUTPRES-UNAME .
    FIELD ZCO_TT_AUTPRES-RESPONSABLE .
    FIELD ZCO_TT_AUTPRES-DENOMINACION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCO_TT_AUTPRES-CODLIB .
    FIELD ZCO_TT_AUTPRES-BUKRS .
    FIELD ZCO_TT_AUTPRES-KOSTL .
    FIELD ZCO_TT_AUTPRES-UNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
