PROCESS BEFORE OUTPUT.

MODULE status_1001.
MODULE INITIALIZATION.

CALL SUBSCREEN sub1001 INCLUDING sy-repid '101'.

PROCESS AFTER INPUT.
CALL SUBSCREEN sub1001.
MODULE INITIALIZATION.
MODULE user_command_1001.



PROCESS ON VALUE-REQUEST.
