PROCESS BEFORE OUTPUT.
MODULE STATUS_1000.
MODULE init.

*   MODULE LOAD_HEADER.
*
PROCESS AFTER INPUT.

MODULE USER_COMMAND_1000.


*PROCESS ON VALUE-REQUEST.
*  FIELD P_ROUTE MODULE INIT_PARAMETERS .
