PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCWS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCWS-ZORDENPM .
    FIELD ZCWS-ZNUMOPER .
    FIELD ZCWS-ZCWID .
    FIELD ZCWS-ZCENTRO .
    FIELD ZCWS-ZPUESTO .
    FIELD ZCWS-ZNUMREC .
    FIELD ZCWS-ZTIEMPOREAL .
    FIELD ZCWS-ZUDM .
    FIELD ZCWS-ZFECHAICW .
    FIELD ZCWS-ZHORAICW .
    FIELD ZCWS-ZFECHAFCW .
    FIELD ZCWS-ZHORAFCW .
    FIELD ZCWS-ZNOTPARFIN .
    FIELD ZCWS-ZNOTANUL .
    FIELD ZCWS-ZFECHACW .
    FIELD ZCWS-ZCONFIRM .
    FIELD ZCWS-ZCONFIRMS .
    FIELD ZCWS-RUECK .
    FIELD ZCWS-RMZHL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCWS-ZORDENPM .
    FIELD ZCWS-ZNUMOPER .
    FIELD ZCWS-ZCWID .
    FIELD ZCWS-ZCENTRO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
