PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFI_REP_CO_GA03 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFI_REP_CO_GA03-PROCESO .
    FIELD ZFI_REP_CO_GA03-ID .
    FIELD ZFI_REP_CO_GA03-CONSE .
    FIELD ZFI_REP_CO_GA03-VALOR .
    FIELD ZFI_REP_CO_GA03-DESCRIPCION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFI_REP_CO_GA03-PROCESO .
    FIELD ZFI_REP_CO_GA03-ID .
    FIELD ZFI_REP_CO_GA03-CONSE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
