PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZHUINV_ITEM CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZHUINV_ITEM-VBELN .
    FIELD ZHUINV_ITEM-POSNR .
    FIELD ZHUINV_ITEM-EXIDV .
    FIELD ZHUINV_ITEM-VENUM .
    FIELD ZHUINV_ITEM-MATNR01 .
    FIELD ZHUINV_ITEM-MATNR02 .
    FIELD ZHUINV_ITEM-MATNR03 .
    FIELD ZHUINV_ITEM-LFIMG01 .
    FIELD ZHUINV_ITEM-LFIMG02 .
    FIELD ZHUINV_ITEM-VRKME .
    FIELD ZHUINV_ITEM-CHARG .
    FIELD ZHUINV_ITEM-CHARG2 .
    FIELD ZHUINV_ITEM-CHARG3 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZHUINV_ITEM-VBELN .
    FIELD ZHUINV_ITEM-POSNR .
    FIELD ZHUINV_ITEM-EXIDV .
    FIELD ZHUINV_ITEM-VENUM .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
