PROCESS BEFORE OUTPUT.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TBC_EBELP'
  MODULE TBC_EBELP_INIT.
*&SPWIZARD: MODULE TBC_EBELP_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TBC_EBELP_CHANGE_COL_ATTR.
  LOOP AT   G_TBC_EBELP_ITAB
       INTO G_TBC_EBELP_WA
       WITH CONTROL TBC_EBELP
       CURSOR TBC_EBELP-CURRENT_LINE.
*&SPWIZARD:   MODULE TBC_EBELP_CHANGE_FIELD_ATTR
    MODULE TBC_EBELP_MOVE.
  ENDLOOP.

 MODULE STATUS_0101.
*
PROCESS AFTER INPUT.
MODULE cancel AT EXIT-COMMAND.

*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TBC_EBELP'
  LOOP AT G_TBC_EBELP_ITAB.
    CHAIN.
      FIELD ZMM_TT_BASCM_SAL-EBELP MODULE CHECK_POS ON CHAIN-REQUEST.
      FIELD ZMM_TT_BASCM_SAL-CASETA MODULE val_caseta on CHAIN-INPUT.
      FIELD ZMM_TT_BASCM_SAL-SEXO MODULE val_sexo on CHAIN-INPUT.
      FIELD ZMM_TT_BASCM_SAL-PZAS MODULE val_pzas on CHAIN-INPUT.
      MODULE TBC_EBELP_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.
  ENDLOOP.

  CHAIN.
    FIELD ZMM_TT_BASCM_SAL-NUM_PESADA MODULE cons_pesada .
     FIELD ZMM_TT_BASCM_SAL-NEA MODULE cons_ticket .
     FIELD ZMM_TT_BASCM_SAL-PESO_SAL module calc_neto_prom.
  ENDCHAIN.

*&SPWIZARD: MODULE TBC_EBELP_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TBC_EBELP_CHANGE_COL_ATTR.

 MODULE USER_COMMAND_0101.
