*&---------------------------------------------------------------------*
*& Include ZMM_APP_BASC_MANUAL_DAT
*&---------------------------------------------------------------------*

***&SPWIZARD: DATA DECLARATION FOR TABLECONTROL 'TBC_EBELP'
*&SPWIZARD: DEFINITION OF DDIC-TABLE
TABLES:   ZMM_TT_BASCM_SAL,zbasculavtas_0.

*&SPWIZARD: TYPE FOR THE DATA OF TABLECONTROL 'TBC_EBELP'
TYPES: BEGIN OF T_TBC_EBELP,
         EBELP LIKE ZMM_TT_BASCM_SAL-EBELP,
         CASETA LIKE ZMM_TT_BASCM_SAL-CASETA,
         SEXO LIKE ZMM_TT_BASCM_SAL-SEXO,
         PZAS LIKE ZMM_TT_BASCM_SAL-PZAS,
       END OF T_TBC_EBELP.

*&SPWIZARD: INTERNAL TABLE FOR TABLECONTROL 'TBC_EBELP'
DATA:     G_TBC_EBELP_ITAB   TYPE T_TBC_EBELP OCCURS 0,
          G_TBC_EBELP_WA     TYPE T_TBC_EBELP. "work area
DATA:     G_TBC_EBELP_COPIED.           "copy flag

*&SPWIZARD: DECLARATION OF TABLECONTROL 'TBC_EBELP' ITSELF
CONTROLS: TBC_EBELP TYPE TABLEVIEW USING SCREEN 0101.

DATA: vg_flag_cons.
