*&---------------------------------------------------------------------*
*&  Include           ZBIPM0005B_DAT
*&---------------------------------------------------------------------*
TABLES:
  IMPTT,
  ILOA,
  EQUZ,
  JEST,
  EQUI.
*types-pool: PMST.
TYPE-POOLS: PMST.
DATA: BEGIN OF BDC_DATA OCCURS 500.
        INCLUDE STRUCTURE BDCDATA.
DATA: END OF BDC_DATA.
* Tabla Interna
DATA: BEGIN OF REC OCCURS 1000,
        EQUNR(18),
        RDCNT(22),
        RDLTS(22),
        IDATE(10),
        ITIME(8),
      END OF REC.

DATA: BEGIN OF I_DISP_LOG OCCURS 0.
        INCLUDE STRUCTURE REC.
DATA: LOG(200),
      END OF I_DISP_LOG.

DATA: BEGIN OF I_REC OCCURS 0.
        INCLUDE STRUCTURE REC.
DATA: TPERR(20),
*  LIKE TABLE OF rec WITH HEADER LINE
      END OF I_REC.
DATA:
  ERROR,
  DIA(2),
  MES1,
  MES2,
  ANIO(2),
  FECHA2(10).
DATA: TYPE LIKE RLGRAP-FILETYPE VALUE 'DAT'.
DATA: LENGTH TYPE I.

DATA: GLOBAL_FILEMASK_ALL(80).
DATA: GLOBAL_FILEMASK_MASK(20), GLOBAL_FILEMASK_TEXT(20),
      FIELDLN TYPE I.
CONSTANTS: C_X VALUE 'X'.
DATA: V_APPEND VALUE C_X.
DATA: I_MESSAGES TYPE BDCMSGCOLL OCCURS 0 WITH HEADER LINE.
DATA: W_LAYOUT TYPE LVC_S_LAYO.
DATA: I_LAYOUT TYPE TABLE OF LVC_S_LAYO.
DATA: W_FIELDCATALOG  TYPE  LVC_S_FCAT.
DATA: I_FIELDCATALOG  TYPE LVC_T_FCAT.

DATA: CC_GRID TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      O_GRID  TYPE REF TO CL_GUI_ALV_GRID.

*-----------  P A R A M E T R O S   -----------------*
SELECTION-SCREEN BEGIN OF BLOCK BLOCK1 WITH FRAME TITLE TEXT-001.
  PARAMETERS: P_FILE LIKE RLGRAP-FILENAME OBLIGATORY
    DEFAULT 'c:\pm20119999.txt'.
*  '\\corinf105\activos\pm1.txt'.

  PARAMETERS: SALVAR NO-DISPLAY, "AS CHECKBOX.
              P_MODE TYPE ZCTU_MODE DEFAULT 'E'.
SELECTION-SCREEN END OF BLOCK BLOCK1.
