PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZPP_TT_SACPREC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZPP_TT_SACPREC-ZWERKS .
    FIELD ZPP_TT_SACPREC-ZSTLNR .
    FIELD ZPP_TT_SACPREC-ZMATNR_SAC .
    FIELD ZPP_TT_SACPREC-ZMATNR_PRE .
    FIELD ZPP_TT_SACPREC-ZCANT_BASE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZPP_TT_SACPREC-ZWERKS .
    FIELD ZPP_TT_SACPREC-ZSTLNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
