*&---------------------------------------------------------------------*
*&  Include           ZREP_BVTAS_TOP
*&---------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*&  Include           ZREP_BASCULA_TOP
*&---------------------------------------------------------------------*

REPORT  ZREP_B_VTAS_UNIF_jhv.
TYPE-POOLS SLIS.

DATA: GO_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      R_LAYOUT     TYPE SLIS_LAYOUT_ALV,
      GO_ALV_GRID  TYPE REF TO CL_GUI_ALV_GRID.

DATA: ZBASCULAVTAS_0  TYPE ZBASCULAVTAS_0.
DATA: ZBASCULAVTAS_1  TYPE ZBASCULAVTAS_1.
DATA: ZBASCULA00      TYPE ZBASCULA00.

DATA: SB0   TYPE ZBASCULAVTAS_0.
DATA: TB1   TYPE STANDARD TABLE OF ZBASCULAVTAS_1.
DATA: SB1   TYPE ZBASCULAVTAS_1.
DATA: SB2   TYPE ZBASCULAVTAS_2.
DATA: TB3   TYPE STANDARD TABLE OF ZBASCULAVTAS_3.
DATA: SB3   TYPE ZBASCULAVTAS_3.
DATA: SB4   TYPE ZBASCULAVTAS_4.
*DATA: sb00  TYPE zbascula00.
*DATA: tb00  TYPE STANDARD TABLE OF zbascula00.

DATA: TFLOW TYPE TDT_DOCFLOW.
DATA: SFLOW LIKE LINE OF TFLOW.
DATA: GD_VBELN_VL TYPE VBELN_VL.

TYPES: BEGIN OF TY_REP.
*   ebeln   TYPE ekko-ebeln,
*   matnr   TYPE ekpo-matnr,
         INCLUDE STRUCTURE ZREP_BASCULA_VTAS.
TYPES: END OF TY_REP.

**DATA: BEGIN OF tt_rep.
**DATA: include TYPE zrep_bascula,
**END OF tt_rep.

DATA: TREP  TYPE STANDARD TABLE OF TY_REP.
DATA: SREP  LIKE LINE OF TREP.

DATA: TFIELDCAT    TYPE SLIS_T_FIELDCAT_ALV,
      SFIELDCAT    LIKE LINE OF TFIELDCAT,

      GT_EVENTS    TYPE SLIS_T_EVENT WITH HEADER LINE,        "ALV table

      GT_SORT      TYPE SLIS_T_SORTINFO_ALV  WITH HEADER LINE, "ALV table
      IT_EVENTEXIT TYPE SLIS_T_EVENT_EXIT,
      WA_EVENTEXIT TYPE SLIS_EVENT_EXIT.

DATA  SVBAP TYPE VBAP.
DATA  SVBAK TYPE VBAK.

DATA: BEGIN OF TAB_KNA1 OCCURS 0.
        INCLUDE STRUCTURE KNA1.
DATA: END OF TAB_KNA1.


SELECTION-SCREEN BEGIN OF BLOCK MAIN WITH FRAME TITLE TEXT-001.

  PARAMETERS:     P_WERKS  TYPE T001W-WERKS.

  SELECT-OPTIONS:
                  SO_ERDAT   FOR ZBASCULAVTAS_0-FECHAPE, " DEFAULT sy-datum,
                  SO_BASNR   FOR ZBASCULA00-BASNR,
                  SO_VBELN   FOR  ZBASCULAVTAS_1-VBELN.

  SELECTION-SCREEN: BEGIN OF BLOCK BLOCK01 WITH FRAME TITLE TEXT-002.
  SELECTION-SCREEN: END OF BLOCK BLOCK01.
SELECTION-SCREEN: END OF BLOCK MAIN.
