PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZSD_TT_PPAEQUSAN CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZSD_TT_PPAEQUSAN-AUART_ECC .
    FIELD ZSD_TT_PPAEQUSAN-AUART_HANA .
    FIELD ZSD_TT_PPAEQUSAN-VKORG_ECC .
    FIELD ZSD_TT_PPAEQUSAN-VKORG_HANA .
    FIELD ZSD_TT_PPAEQUSAN-VTWEG_ECC .
    FIELD ZSD_TT_PPAEQUSAN-VTWEG_HANA .
    FIELD ZSD_TT_PPAEQUSAN-SPART_ECC .
    FIELD ZSD_TT_PPAEQUSAN-SPART_HANA .
    FIELD ZSD_TT_PPAEQUSAN-VKBUR_ECC .
    FIELD ZSD_TT_PPAEQUSAN-VKBUR_HANA .
    FIELD ZSD_TT_PPAEQUSAN-VKGRP_ECC .
    FIELD ZSD_TT_PPAEQUSAN-VKGRP_HANA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZSD_TT_PPAEQUSAN-AUART_ECC .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
